<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>请点击按钮</title>
    <style>
        body {
            background-color: black;
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
        }
        #buttonContainer {
            position: relative;
            width: 100%;
            height: 100%;
        }
        button {
            font-size: 16px;
            font-weight: bold;
            color: white;
            padding: 15px 25px;
            border: none;
            cursor: pointer;
            border-radius: 15px;
            transition: transform 0.2s ease-in-out;
            position: absolute;
            background-color: #333; /* Default background color */
        }
        .circle {
            border-radius: 50%;
        }
        .square {
            border-radius: 0;
        }
        .rounded {
            border-radius: 15px;
        }
        button:hover {
            transform: scale(1.05); /* Slightly enlarge on hover */
        }
        @keyframes float {
            0%, 100% { transform: translateY(0px); }
            50% { transform: translateY(-10px); }
        }
        .float {
            animation: float 3s ease-in-out infinite;
        }
    </style>
</head>
<body>
    <!-- <h2 style="color: white;text-align: center;">任意门</h2> -->
    <div id="buttonContainer">
        <!-- Buttons will be generated by PHP -->
        <?php
        $shapes = ['circle', 'square', 'rounded'];
        for ($i = 0; $i < 100; $i++) {
            $randomColor = sprintf('#%06X', mt_rand(0, 0xFFFFFF));
            $randomShape = $shapes[array_rand($shapes)];
            echo '<a href="flag' . $i . '.php" target="_blank"><button class="' . $randomShape . '" style="background-color:' . $randomColor . ';">Flag ' . $i . '</button></a>';
        }  
        ?>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const buttons = document.querySelectorAll('button');
            buttons.forEach(button => {
                // Random initial position
                const x = Math.random() * (window.innerWidth - button.offsetWidth);
                const y = Math.random() * (window.innerHeight - button.offsetHeight);
                button.style.left = `${x}px`;
                button.style.top = `${y}px`;

                // Apply float animation
                button.classList.add('float');

                // Random movement
                const move = () => {
                    const newX = Math.random() * (window.innerWidth - button.offsetWidth);
                    const newY = Math.random() * (window.innerHeight - button.offsetHeight);
                    button.style.left = `${newX}px`;
                    button.style.top = `${newY}px`;
                };
                setInterval(move, 5000); // Move every 5 seconds
            });
        });
    </script>
</body>
</html>

